config/routes.rb
Flitter::Application.routes.draw do

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users
  
  resources :flits
  
  match '/search', :to => 'home#search', :as => :search, :via => "post"
  
  match '/remove_friend/:username', :to => 'home#remove_friend', :as => :remove_friend, :via => "post"
  
  match '/following', :to => 'home#following', :as => :following
    
  match '/:username', :to => 'home#show', :as => :user_flits
  
  match '/:username/toggle_follow', :to => 'home#toggle_follow', :as => :toggle_follow
  
  match '/:username/toggle_follow_via_ajax', :to => 'home#toggle_follow_via_ajax', :as => :toggle_follow_via_ajax

  root :to => "home#index"

end

app/views/includes/_side_contents.html.erb
<div id="my_info_container">
	<%= link_to image_tag('/images/avatar.jpg', :border => 0), user_flits_path(current_user.username) %>
	<div class="contents">
		<%= link_to current_user.username, user_flits_path(current_user.username) %><br/>
		<span class="small"><%= pluralize(current_user.flits.length, "Flit" ) %></span>
	</div>
</div>
<div class="clear"></div>

<div id="side_content_container">
	<h4><%= link_to "#{current_user.friends.count} following", following_path %></h4>
	<h4><%= pluralize(current_user.friends_of.count, "follower") %></h4>
</div>

<% form_tag search_path do %>
<div id="search_bar">
	<%= text_field_tag :q, @q, :class => "text" %>
	<div id="search_submit_button">&nbsp;

	</div>
</div>
<% end %>

<div id="side_content_container">
	<h4>Followers</h4>
	<% current_user.friends_of.each do |friend| %>
		<%= link_to image_tag('/images/avatar_30.gif', :border => 0, :alt => friend.username, :title => friend.username), user_flits_path(friend.username) %>
	<% end %>
</div>