config/routes.rb
Flitter::Application.routes.draw do

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users
  
  resources :flits
  
  match '/search', :to => 'home#search', :as => :search, :via => "post"
  
  match '/remove_friend/:username', :to => 'home#remove_friend', :as => :remove_friend, :via => "post"
  
  match '/following', :to => 'home#following', :as => :following
    
  match '/:username', :to => 'home#show', :as => :user_flits
  
  match '/:username/toggle_follow', :to => 'home#toggle_follow', :as => :toggle_follow
  
  match '/:username/toggle_follow_via_ajax', :to => 'home#toggle_follow_via_ajax', :as => :toggle_follow_via_ajax

  root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_filter :login_required
  
  def index
    @flits = current_user.all_flits
    @last_flit = current_user.flits.last
  end
  
  def show
    @user = User.find_by_username(params[:username])
    @flits = @user.flits
  end
  
  def toggle_follow
    @user = User.find_by_username(params[:username])
    if current_user.is_friend? @user
      flash[:notice] = "You are no longer following @#{@user.username}"
      current_user.remove_friend(@user)
    else
      flash[:notice] = "You are now following @#{@user.username}"
      current_user.add_friend(@user)
    end
    redirect_to user_flits_path(@user.username)
  end
  
  def toggle_follow_via_ajax
    user = User.find_by_username(params[:username])
    if current_user.is_friend? user
      current_user.remove_friend(user)
    else
      current_user.add_friend(user)
    end
    render :text => user.username
  end
  
  def following
    @friends = current_user.friends
  end
  
  def remove_friend
    friend = User.find_by_username(params[:username])
    if friend
      current_user.remove_friend(friend)
      render :text => friend.username
    else
      render :text => "None"
    end
  end
  
  def search
    @q = params[:q]
    @friends = User.excluding(current_user).like(@q)
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_flits_list.html.erb
<ul id="flits_list">
	<% flits.each do |flit| %>
	<li<% if flits.first == flit %> class="first"<% end %>>
		<%= image_tag '/images/avatar.jpg' %>
		<div class="flit_message_container">
			<%= link_to flit.user.username, user_flits_path(flit.user.username) %>
			<%= h flit.message %>
			<div class="time_ago">
				<%= distance_of_time_in_words_to_now(flit.created_at) %> ago
			</div>
		</div>
		<div class="clear"></div>
	</li>
	<% end %>
</ul>

app/views/home/following.html.erb
<ul id="flits_list">
	<% @friends.each do |friend| %>
	<li<% if @friends.first == friend %> class="first"<% end %> id="<%= friend.username %>">
		<%= image_tag '/images/avatar.jpg' %>
		<div class="flit_message_container" style="width: 305px;">
			<h3><%= link_to friend.username, user_flits_path(friend.username) %></h3>
			<% if friend.flits.length > 0 %>
				<%= h friend.flits.last.message %>
				<div class="time_ago">
					<%= distance_of_time_in_words_to_now(friend.flits.last.created_at) %> ago
				</div>
			<% end %>
		</div>
		<div class="button container">
			<input type="button" name="<%= friend.username %>" class="button ajax_button" value="Stop Following"/>
		</div>
		<div class="clear"></div>
	</li>
	<% end %>
</ul>

<script type="text/javascript">
$(function() {
	$('.ajax_button').click(function() {
		$.ajax({
			type: "POST",
			url: "/remove_friend/" + $(this).attr('name'),
			success: function(msg){
				//alert( "You are no longer following: " + msg);
				$('#' + msg).slideUp('slow');
			}
		});
	})
});
</script>

app/views/home/index.html.erb
<script type="text/javascript">
$(function() {
	$('#flit_message').keyup(function() {
		var content_length = $(this).val().length;
		var remaining = 140 - content_length
		$('#char_count').html(remaining);
		if (remaining < 20 && remaining > 9) {
			$('#char_count').removeClass('red');
			$('#char_count').addClass('dark_red');
		}   else if (remaining <= 9) {
			$('#char_count').removeClass('dark_red');
			$('#char_count').addClass('red');
		}   else {
			$('@char_count').removeClass('dark_red').removeClass('red');
		}
	})
})
</script>

<%- form_for Flit.new do |f| -%>
	<div id="new_flit_form">
		<h3 style="float: left;">What are you doing?</h3>
		<h3 id="char_count">140</h3>
		<div class="clear"></div>
		<%= f.text_area :message %>
		<% if current_user.flits.length > 0 %>
	 		<div id="latest_message">
	 			<strong>Latest: </strong><%= @last_flit.message %>
	 			<%= distance_of_time_in_words_to_now(@last_flit.created_at) %> ago
	 		</div>
		<% end %>
		<div id="submit_button_container">
			<%= f.submit "update", :class => "button" %>
		</div>
		<div class="clear"></div>
	</div>
<%- end -%>

<%= render :partial => "flits_list", :locals => { :flits => @flits } %>

app/views/home/search.html.erb
<ul id="flits_list">
  <% @friends.each do |friend| %>
    <li<% if @friends.first == friend %> class="first"<% end %> id="<%= friend.username %>">
      <%= image_tag '/images/avatar.jpg' %>
      <div class="flit_message_container" style="width: 305px;">
        <h3><%= link_to friend.username, user_flits_path(friend.username) %></h3>
        <% if friend.flits.length > 0 %>
          <%= h friend.flits.last.message %>
          <%= distance_of_time_in_words_to_now(friend.flits.last.created_at) %> ago
        <% end %>
      </div>
      <div class="button_container">
        <input type="button" name="<%= friend.username %>" id="btn_<%= friend.username %>" class="button ajax_button"
          value="<% if current_user.is_friend? friend %>Stop Following<% else %>Follow<% end %>"/>
      </div>
      <div class="clear"></div>
    </li>
  <% end %>
</ul>

<script type="text/javascript">
$(function() {
  $('.ajax_button').click(function() {
    $.ajax({
       type: "POST",
       url: "/" + $(this).attr('name') + "/toggle_follow_via_ajax",
       success: function(msg){
         elm = $('#btn_' + msg);
         if (elm.val() == "Stop Following") {
           elm.val("Follow");
         } else {
           elm.val("Stop Following");
         }
       }
     });
  })
});
</script>

app/views/home/show.html.erb
<h1><%= image_tag('/images/avatar.jpg', :align => "top") %> <%= @user.username %></h1>

<%- form_tag toggle_follow_path do -%>
	<% if current_user.is_friend? @user %>
		<%= submit_tag "Following", :class => "button" %>
	<% else %>
		<%= submit_tag "Not Following", :class => "button" %>
	<% end %>
<%- end -%>

&nbsp;

<%= render :partial => "flits_list", :locals => { :flits => @flits } %>