config/routes.rb
Flitter::Application.routes.draw do

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users
  
  resources :flits
  
  match '/search', :to => 'home#search', :as => :search, :via => "post"
  
  match '/remove_friend/:username', :to => 'home#remove_friend', :as => :remove_friend, :via => "post"
  
  match '/following', :to => 'home#following', :as => :following
    
  match '/:username', :to => 'home#show', :as => :user_flits
  
  match '/:username/toggle_follow', :to => 'home#toggle_follow', :as => :toggle_follow
  
  match '/:username/toggle_follow_via_ajax', :to => 'home#toggle_follow_via_ajax', :as => :toggle_follow_via_ajax

  root :to => "home#index"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "/javascripts/jquery.js" %> <!--HACK--> 
    <%= javascript_include_tag "/javascripts/jquery-ui.js" %> <!--HACK-->
    <%= javascript_include_tag "/javascripts/jrails.js" %> <!--HACK-->
    <%= javascript_include_tag "/javascripts/application.js" %> <!--HACK-->
    <%= yield(:head) %>
  </head>
  <body>
    <div id="header">
		<div id="logo">
			<%= image_tag("logo.png", :alt => "Flitter") %>
		</div>
		<div id="top_links_container">
			<% if current_user %>
				logged in as <%= current_user.username %> | 
				<%= link_to "logout", logout_path %>
			<% else %>
				<%= link_to "login", login_path %>
			<% end %>
		</div>
		<div class="clear"></div>
	</div>
	<div id="container">
		<div id="main">
      		<% flash.each do |name, msg| %>
        		<%= content_tag :div, msg, :id => "flash_#{name}" %>
      		<% end %>
     		<%= content_tag :h1, yield(:title) if show_title? %>
      		<%= yield %>
		</div>
		<div id="side">
			<% if current_user %>
				<%= render :partial => "/includes/side_contents" %>	
			<% end %>
		</div>
		<div class="clear"></div>
    </div>
  </body>
</html>